name: ajanda_uygulama
description: "A new Flutter project."
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.2.0 <4.0.0'

dependencies:
  flutter:
    sdk: flutter
  
  # DÜZELTME: Bu paketler en sola yaslı değil, 'flutter:' kelimesiyle aynı hizada olmalı.
  # 'sdk: flutter' satırının altında olmamalı.
  http: ^1.2.0
  intl: ^0.19.0
  shared_preferences: ^2.2.2
  
  # İkonlar için genelde gereklidir
  cupertino_icons: ^1.0.6
  permission_handler: ^12.0.1
  introduction_screen: ^4.0.0
  fl_chart: ^1.1.1
  confetti: ^0.8.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^3.0.0

flutter:
  uses-material-design: true